name: CI

on:
  push:
    tags:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        run: docker login --username=${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Image
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t mmdjiji/terraria-server:latest -t mmdjiji/terraria-server:${{ github.ref_name }} .